### ISSUE TITLE
bridgecrewio/checkov can't be updated due to IP restriction

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua-registry-updater#549]
- https://github.com/aquaproj/aqua-registry/issues/30787#issuecomment-2608831916

> 403 Although you appear to have the correct authorization credentials, the bridgecrewio organization has an IP allow list enabled, and your IP address is not permitted to access this resource.

But `aqua g bridgecrewio/checkov` can get the latest version.

```console
$ aqua g bridgecrewio/checkov
- name: bridgecrewio/checkov@3.2.355
```

**Comment by suzuki-shunsuke** [comment]
Test

- https://github.com/suzuki-shunsuke/test-github-action/pull/285

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua-registry/actions/runs/12927541803/job/36052887007?pr=31265
- https://github.com/aquaproj/aqua-registry/pull/31265

```yaml
      - run: aqua g bridgecrewio/checkov # Success
      - run: aqua g bridgecrewio/checkov # Fail
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: aqua g bridgecrewio/checkov # Fail
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
```
